### ISSUE TITLE
Create initial developer hub mockup based on developer user stories.

### ISSUE THREAD

**Issue by cedwards-reisys** [18F/data-act-usaspending#3]

**Comment by AGuyNamedMarco** [comment]
![wireframe_dev-hub_03-01](https://cloud.githubusercontent.com/assets/5605410/8682517/7349826a-2a3b-11e5-8e03-2b8311b405b0.png)

**Comment by socrata-matthewvb** [comment]
Will this include any functionality around testing various calls? Also, I'd include example queries and what response they'll return.

**Comment by AGuyNamedMarco** [comment]
This layout utilizes Swagger's API documentation output.

Here's an example:
http://petstore.swagger.io/

**Comment by AGuyNamedMarco** [comment]
@socrata-matthewvb Good ideas.  Swagger does have an interactive testing function which come stock with its output, so that will be included.
