### ISSUE TITLE
Task - Set up a meeting with 18F to walk through what the grants data element are that have been collected for SBA

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#30]

**Comment by socrata-matthewvb** [comment]
Targeting a mtg with Becky on/around the 22nd to follow-up with her.

**Comment by socrata-matthewvb** [comment]
Still waiting to hear back from Becky. She was on vaca for the past few days.

**Comment by socrata-matthewvb** [comment]
Becky and I met - decided we'd continue to chat in upcoming weeks as the data gets more refined and the schema updated. SBA is on a break from the project for a few weeks it sounds like. Becky is working on new "fake" data using the updated schema and will send it over.
