### ISSUE TITLE
Task - Set up a meeting with SBA to walk through what they would like to see done with the data collected for DATA Act

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#31]

**Comment by bsweger** [comment]
Jumping in on this one b/c there's crossover with the SBA pilot. Paging @andrewmaiew!

**Comment by socrata-matthewvb** [comment]
@yehk - this isn't my task, assigning back to you.

**Comment by yehk** [comment]
Closed. This story is no longer needed.
