### ISSUE TITLE
Task - Ingest USAspending data for 2013 and 2014 into the Socrata platform

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#34]

**Comment by socrata-matthewvb** [comment]
We most likely won't do this as we're running into data issues. Backup plan is to only ingest the columns required to map to Open Expenditures and then ingest those columns for all 2013/2014.

**Comment by socrata-matthewvb** [comment]
We're marking this as pseudo-blocked until we determine whether we need to upload it all. It'll take a larger effort due to the data quality issues.

**Comment by socrata-matthewvb** [comment]
Continuing with plan to only ingest the relevant fields for OE right now.

**Comment by socrata-matthewvb** [comment]
100% 2013 uploaded. 50%+ 2014 uploaded. Currently still in process.

**Comment by socrata-matthewvb** [comment]
https://treasury-data-act.demo.socrata.com/dataset/Contract-Expenditures/u9xa-dsbd
