### ISSUE TITLE
Task - If the mapping is over 80% open expenditures will be launched

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#36]

**Comment by socrata-matthewvb** [comment]
Dependent on #35

**Comment by socrata-matthewvb** [comment]
We've set up a demo of this but need to re-ingest the data to fit the updated mapping. I'll share out the demo site once it's ready (mid-next week).

**Comment by socrata-matthewvb** [comment]
Continuing to re-ingest the data.

**Comment by socrata-matthewvb** [comment]
http://contracts.expenditures-demo.socrata.com/#/
username: demo
password: demo
