### ISSUE TITLE
As a developer, I need ways to have two-way communication with user community. (e.g. Twitter account, GitHub issues, etc.)

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#41]
Acceptance Criteria:
- [ ] GitHub anonymous/API
- [ ] GitHub not anonymous
- [ ] Email set up
- [ ] Create Twitter

**Comment by cedwards-reisys** [comment]
Using an off-shelf feedback module for Drupal.  It's buggy.  https://www.drupal.org/project/feedback

**Comment by cedwards-reisys** [comment]
I recommend building our own feedback service or using a commercial service.

**Comment by yehk** [comment]
Duplicate - Closed
