### ISSUE TITLE
As an end user, I need further development of content to make the site more informative.

### ISSUE THREAD

**Issue by msathyaraj2015** [18F/data-act-usaspending#54]
Acceptance Criteria:
- [ ] Place additional content on beta site prior to release.

**Comment by USAspendingalice** [comment]
I have added Draft content to the Home Page and the About page.  Will talk to Chris about adding the one line of content to the Search Results and Developer Hub pages.

**Comment by yehk** [comment]
Closed. This is recaptured in Story 72. Duplicate.
