### ISSUE TITLE
As the product owner, I need to determine the process for managing feedback.

### ISSUE THREAD

**Issue by msathyaraj2015** [18F/data-act-usaspending#56]
Acceptance Criteria:
- [x] Determine who is going to moderate the feedback
- [x] Propose a process for triaging feedback
- [x] Provide rules for display on the community forum
- [x] Identify statistical tracking method for similar requests

**Comment by yehk** [comment]
vBulletin does not have additional statistical data. Will rely on Google Analytics.

**Comment by askamp101** [comment]
Issue Tracker for week of 11/10 
[Beta_Forum_Issue_Tracker.xlsx](https://github.com/18F/data-act-usaspending/files/35805/Beta_Forum_Issue_Tracker.xlsx)
