### ISSUE TITLE
Download and ingest all prime contract data for FY13 and FY14 from USASpending into Socrata portal.

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#62]

**Comment by cmpera** [comment]
- all contract data for FY13 and FY14 have been uploaded to production instance of Socrata (see card #64)
  - available at: fedspending.demo.socrata.com/d/3kp6-u7ur

**Comment by cmpera** [comment]
view of Contract data in grid format: https://fedspending.demo.socrata.com/d/3kp6-u7ur
view of Contract data for API call to be used by Chris: https://fedspending.demo.socrata.com/d/nfu7-rhaq
