### ISSUE TITLE
Determine URL for Socrata instance

### ISSUE THREAD

**Issue by socrata-matthewvb** [18F/data-act-usaspending#63]

**Comment by socrata-matthewvb** [comment]
Assigning this to Manoj for tracking - not sure if Neeraj has an account yet.

**Comment by cmpera** [comment]
We potentially need 3 sub-domains.... 
- 1 for the data hosting site
- 1 for the Open Budget app
- 1 for the Open Expenditures app

consider:
- data.fedspending.gov (required for accessing API end point)
- openbudget.fedspending.gov
- openexpenditures.fedspending.gov

**Comment by cmpera** [comment]
_updated URLs:_
- data.fedspending.gov
-  grants-explorer.fedspending.gov
-  contracts-explorer.fedspending.gov
