### ISSUE TITLE
Set up a production instance of Socrata for August launch

### ISSUE THREAD

**Issue by socrata-matthewvb** [18F/data-act-usaspending#64]

**Comment by cmpera** [comment]
- created a production instance of Socrata
  - currently available at: fedspending.demo.socrata.com
  - site still has "login restrictions" enabled but API is available to use in buildout of prototype by Chris
  - waiting on confirmation from Neeraj and Manoj if we will change from a .socrata.com URL to a production-ready URL (see card #63)
