### ISSUE TITLE
I need a logo for the beta site

### ISSUE THREAD

**Issue by cmpera** [18F/data-act-usaspending#68]
Acceptance Criteria:
- [x] Provide logo

**Comment by cmpera** [comment]
Hi Alice,

Would it be possible to create or share a fedspending logo that we could try and incorporate into the apps?

**Comment by USAspendingalice** [comment]
Christina suggested a logo that I sent to Marco on Wednesday.

**Comment by AGuyNamedMarco** [comment]
![fedspending_logo](https://cloud.githubusercontent.com/assets/5605410/9363692/deb16030-4675-11e5-8f59-001ac5737904.png)
