### ISSUE TITLE
As a product owner, I want to provide the end user with a gallery of visualizations.

### ISSUE THREAD

**Issue by cedwards-reisys** [18F/data-act-usaspending#70]

**Comment by cmpera** [comment]
_app in highlight #1:_
- _name:_ Grants Explorer
- _url:_ grants-explorer.fedspending.gov
- _description:_ 
  The Grants Explorer is an interactive display of the DATA Act Pilot Data provided to Treasury by the Small Business Administration (SBA) for FY13 and FY14.  Visitors can visualize trends in grantee awards, compare obligations and outlays, and see the results of data-driven decision making.  Visitors can access the data via full-text search, API access, or download the data in a variety of options.
- _image asset:_ 
  *\* _available here_ - https://drive.google.com/folderview?id=0ByFk2-WUxOsHfmJSaVgzTXdYNzlJNWZjbFk0WlJfbm1reVk0MUI4YlZLb0lLcEZsd1lqVFU&usp=sharing
  *\* _see:_ grants-explorer_screenshot1 OR grants-explorer_screenshot2

**Comment by cmpera** [comment]
_app in highlight #2:_
- _name:_ Contracts Explorer
- _url:_ contracts-explorer.fedspending.gov
- _description:_ 
  The Contracts Explorer is an interactive display of USASpending contract data for all submitting agencies for FY13 and FY14.  Visitors can visualize spending trends, compare expenditures across expense categories, and see detailed transactions. Advanced users can visualize the data using advanced tools including filtered views, roll ups, and custom visualizations.  Full-text search, API access, and data is downloaded in a variety of options.  
- _image asset:_ 
  *\* _available here_ - https://drive.google.com/folderview?id=0ByFk2-WUxOsHfmJSaVgzTXdYNzlJNWZjbFk0WlJfbm1reVk0MUI4YlZLb0lLcEZsd1lqVFU&usp=sharing
  *\* _see:_ contracts-explorer_screenshot1 OR contracts-explorer_screenshot2

**Comment by cmpera** [comment]
assigning to @cedwards-reisys for implementation

**Comment by cedwards-reisys** [comment]
Create a Visualization content type in Drupal.  Built the /gallery page using the Views module.  http://ec2-54-152-196-147.compute-1.amazonaws.com/gallery
