### ISSUE TITLE
Punch list for beta launch

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#72]
Acceptance Criteria:

Visualization gallery:
- [x] Update text - CP
- [x] Cname - CP
- [x] Screenshots - CP
- [x] Swap in grants data - CP
- [x] Data standardization of procurement data - CP

Feedback module:
- [x] Webform - CE
- [x] Implement reCAPTCHA - CE 
- [x] Get Google account for reCAPTCHA - AS
- [x] Get Google account for Google Analytics - AS
- [x] Implement Google Analytics - CE
- [x] Investigate vBulletin test trial - CE
- [x] Infrastructure for vBulletin - MS
- [x] Security impact for vBulletin - MS
- [x] **Set up vBulletin - CE**
- [x] **Set up theme for vBulletin - MM**
- [x] Email setup - MS
- [x] **Incorporate feedback email in web form - CE**

Production servers:
- [x] Configure Production servers - CE

Known issues:
- [x]  **Develop list of known issues (Need to change to name to not include "issues") - CE/MM**

Security:
- [ ] ATO security package - MS
- [x] CR for DNS - MS
- [x] Schedule scans - MS
- [x] Security discussion/meeting (hopefully everyone is like minded) - CH/MS
- [x] SSL certificates - MS

Add Content:
- [x] **Home and About pages - CH/AS**
- [x] **Developer page - CE/AS/MM**
- [x] **Feedback page (Clarify distinction between Bulletin board versus web form)- CH/AS**

API performance:
- [x] API performance improvement - CS

Load Testing:
- [x] Research the load test process - MS/CE

Site embargo:
- [x] Site embargo execution - MS

Feedback process:
- [ ] Set up business business process to manage feedback workflow (including web form and vBulletin) - CH/MS/MU

Theme for entire site:
- [x] **Theme enhancement (Apply bolder color pallet to header, illustrative treatment to main pages, etc.) - MM**

**Comment by msathyaraj2015** [comment]
CR#: SD0001036593

**Comment by cmpera** [comment]
As requested, here are the standardization steps we took on the Contracts data for the Contracts Explorer 
(note: these standardization steps were _not_ applied to the contracts data being used for fedspending.gov search):
- First set fields (maj_agency_cat and fundingrequestingagencyid) be UPPERCASE
- If field had the word DEPT or DEPARTMENT in it, we removed all instances of: ", DEPT OF THE", "DEPT OF THE", "DEPT OF", ", DEPARTMENT OF THE", "DEPARTMENT OF THE", "DEPARTMENT OF"
- Then we searched for the ":" and replaced it with ": DEPT OF" so it was alway #: DEPT OF {{department name}}

**Comment by yehk** [comment]
Removing acceptance criteria for ATO and Feedback Business process to feature stories.
