### ISSUE TITLE
As a user, I want the next generation of contracts explorer app.

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#77]
Acceptance Criteria:
- [x] User experience is aligned with Grants Explorer
- [x] Additional functionality

**Comment by cmpera** [comment]
**current version:** contracts-explorer.fedspending.gov
**updated version:** treasurycontracts.spending.socrata.com

Will move updated version to final URL (contracts-explorer.fedspending.gov) once approved.
