### ISSUE TITLE
As a Product Owner, I want to see a sampling of search options.

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#78]
Acceptance Criteria:
- [x] Provide wireframes for different search options

**Comment by AGuyNamedMarco** [comment]
<img width="1392" alt="00_search_concepts-search_page" src="https://cloud.githubusercontent.com/assets/5605410/10110363/bd9b3988-639a-11e5-821d-d5ec476926af.png">
<img width="1392" alt="01_search_concepts-live_filters" src="https://cloud.githubusercontent.com/assets/5605410/10110364/bd9b3d20-639a-11e5-96e5-8f0a41722e08.png">
<img width="1392" alt="02_search_concepts-adv_search" src="https://cloud.githubusercontent.com/assets/5605410/10110361/bd9aee4c-639a-11e5-928e-240605268e7f.png">
<img width="1392" alt="03_search_concepts-search_builder" src="https://cloud.githubusercontent.com/assets/5605410/10110365/bd9b71e6-639a-11e5-9a15-b458dc3cd676.png">
<img width="1392" alt="04_search_concepts-sql_search" src="https://cloud.githubusercontent.com/assets/5605410/10110362/bd9b2326-639a-11e5-9933-a7fff2757288.png">
