### ISSUE TITLE
As a user, I want to see updates to the new version of the contracts explorer.

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#83]
Acceptance Criteria
- [x] Update the banner image and home page text
- [x] Enable the vendor flags
- [x] Review data model with SME
- [x] Swap the old version of the App with the new version of the App.

**Comment by cmpera** [comment]
Enabling the vendor flags is currently in the works. Will review the data, per Alice's guidance on Friday, and update accordingly.

**Comment by cmpera** [comment]
**example contract with vendor flag:**
http://contracts-explorer.fedspending.gov/#!/year/2014/explore/0/vendorname/POWERTRAIN+INC/0/maj_fund_agency_cat_standardized
