### ISSUE TITLE
As a product owner, I need to determine a new domain name.

### ISSUE THREAD

**Issue by msathyaraj2015** [18F/data-act-usaspending#86]
Acceptance Criteria:
- [x] Determine what the new domain will be
- [x] Modify the Logo to reflect the new domain name.
- [x] Update content as necessary
- [x] Update Google Analytics for updated name
- [x] Update Mailbox
- [x] Update recapcha for new name

**Comment by yehk** [comment]
openbeta.usaspending.gov

**Comment by drewleety** [comment]
Closed
