### ISSUE TITLE
As a website user, I need a way to close an open visualization without having to click off the open visualization

### ISSUE THREAD

**Issue by drewleety** [18F/data-act-usaspending#89]
Acceptance Criteria: 
- [x] Close button (X) is added to the visualization window (Changed criteria to match normal temporary pop ups which is to disappear when the cursor is removed.)

**Comment by cedwards-reisys** [comment]
Is this on the concepts page? http://cl.ly/image/0r2t1p2W3a0s   There is a close button on the top right corner.

**Comment by AGuyNamedMarco** [comment]
Someone correct me if wrong, but I believe this is referring to the Live Filters demo.

When clicking on the Award ID, a pop-up box appears with the description and the only way to close it is to click the Award ID again.

The solution suggested was to add an X icon to close the description, but I think we should consider having the functionality of the display to be on hover of the Award ID link, and closing it when hovering off of the row.

**Comment by cedwards-reisys** [comment]
Hover makes it impossible to copy any text from the popover.

**Comment by cedwards-reisys** [comment]
This is what it's using:  http://getbootstrap.com/javascript/#popovers
