### ISSUE TITLE
As a website user, I need to be able to run a search on Award ID in the filter search tool.

### ISSUE THREAD

**Issue by drewleety** [18F/data-act-usaspending#90]
Acceptance Criteria:  
- [x] Data sorting should be disabled until user selects a column to sort on.
- [x] Sorting will be initially disabled whenever search params are changed or cleared

**Comment by cedwards-reisys** [comment]
Does this apply to to the live filters demo from the concepts page?  The Award ID is searchable. http://cl.ly/image/0R051A161q0y

**Comment by cedwards-reisys** [comment]
This is the query that would run.  https://openbeta-data.usaspending.gov/resource/2gu8-h37q.json?%24q=N0002412C2115&%24select=descriptionofcontractrequirement%2Cvendorname%2Cpiid%2Cdollarsobligated%2Csigneddate%2Cmaj_agency_cat%2Cmaj_fund_agency_cat&%24offset=0&%24limit=20&%24order=dollarsobligated+desc
